import React from "react";
import { Box } from "@mui/material";
import { DataGrid, GridColDef } from "@mui/x-data-grid";
const data = [
  {
    id: 1,
    first_name: "Arni",
    last_name: "Stillwell",
    email: "astillwell0@theguardian.com",
    gender: "Male",
    ip_address: "106.222.244.175",
  },
  {
    id: 2,
    first_name: "Lewie",
    last_name: "McCarty",
    email: "lmccarty1@blog.com",
    gender: "Male",
    ip_address: "90.59.192.159",
  },
  {
    id: 3,
    first_name: "Janean",
    last_name: "Colledge",
    email: "jcolledge2@merriam-webster.com",
    gender: "Female",
    ip_address: "61.101.84.155",
  },
  {
    id: 4,
    first_name: "Lyman",
    last_name: "Harberer",
    email: "lharberer3@bbb.org",
    gender: "Genderfluid",
    ip_address: "30.10.172.253",
  },
  {
    id: 5,
    first_name: "Gregg",
    last_name: "Gloucester",
    email: "ggloucester4@de.vu",
    gender: "Male",
    ip_address: "83.38.203.139",
  },
  {
    id: 6,
    first_name: "Olympia",
    last_name: "Shalloo",
    email: "oshalloo5@de.vu",
    gender: "Female",
    ip_address: "69.164.41.134",
  },
  {
    id: 7,
    first_name: "Emiline",
    last_name: "Rude",
    email: "erude6@dailymail.co.uk",
    gender: "Female",
    ip_address: "220.235.9.182",
  },
  {
    id: 8,
    first_name: "Paula",
    last_name: "Dressel",
    email: "pdressel7@usatoday.com",
    gender: "Female",
    ip_address: "248.133.165.82",
  },
  {
    id: 9,
    first_name: "Manny",
    last_name: "Peddie",
    email: "mpeddie8@naver.com",
    gender: "Male",
    ip_address: "30.56.22.174",
  },
  {
    id: 10,
    first_name: "Constantine",
    last_name: "Abdee",
    email: "cabdee9@cornell.edu",
    gender: "Female",
    ip_address: "251.95.98.167",
  },
  {
    id: 11,
    first_name: "Reagen",
    last_name: "Matitiaho",
    email: "rmatitiahoa@berkeley.edu",
    gender: "Male",
    ip_address: "37.142.238.95",
  },
  {
    id: 12,
    first_name: "Carolina",
    last_name: "Cordier",
    email: "ccordierb@hugedomains.com",
    gender: "Female",
    ip_address: "138.246.210.99",
  },
  {
    id: 13,
    first_name: "Lynn",
    last_name: "Dadge",
    email: "ldadgec@sakura.ne.jp",
    gender: "Female",
    ip_address: "66.105.201.237",
  },
  {
    id: 14,
    first_name: "Rubina",
    last_name: "Bercher",
    email: "rbercherd@ifeng.com",
    gender: "Female",
    ip_address: "146.201.111.178",
  },
  {
    id: 15,
    first_name: "Brigham",
    last_name: "Purrington",
    email: "bpurringtone@nydailynews.com",
    gender: "Male",
    ip_address: "190.76.9.19",
  },
  {
    id: 16,
    first_name: "Beitris",
    last_name: "Baxster",
    email: "bbaxsterf@ucoz.ru",
    gender: "Female",
    ip_address: "158.182.228.95",
  },
  {
    id: 17,
    first_name: "Rachele",
    last_name: "Freke",
    email: "rfrekeg@hp.com",
    gender: "Female",
    ip_address: "34.70.57.160",
  },
  {
    id: 18,
    first_name: "Lee",
    last_name: "Bambury",
    email: "lbamburyh@51.la",
    gender: "Male",
    ip_address: "212.224.29.221",
  },
  {
    id: 19,
    first_name: "Webb",
    last_name: "Aberhart",
    email: "waberharti@istockphoto.com",
    gender: "Male",
    ip_address: "235.37.90.41",
  },
  {
    id: 20,
    first_name: "Alvan",
    last_name: "Peller",
    email: "apellerj@weather.com",
    gender: "Male",
    ip_address: "117.206.9.96",
  },
  {
    id: 21,
    first_name: "Aron",
    last_name: "Hexham",
    email: "ahexhamk@liveinternet.ru",
    gender: "Male",
    ip_address: "17.4.9.152",
  },
  {
    id: 22,
    first_name: "Sioux",
    last_name: "Breawood",
    email: "sbreawoodl@weibo.com",
    gender: "Female",
    ip_address: "232.223.133.215",
  },
  {
    id: 23,
    first_name: "Tonie",
    last_name: "Delwater",
    email: "tdelwaterm@comsenz.com",
    gender: "Female",
    ip_address: "182.243.60.118",
  },
  {
    id: 24,
    first_name: "Stephen",
    last_name: "Rickett",
    email: "srickettn@nyu.edu",
    gender: "Male",
    ip_address: "209.10.32.51",
  },
  {
    id: 25,
    first_name: "Gilemette",
    last_name: "Hargie",
    email: "ghargieo@google.com.hk",
    gender: "Female",
    ip_address: "192.120.72.247",
  },
  {
    id: 26,
    first_name: "Gilburt",
    last_name: "Langton",
    email: "glangtonp@taobao.com",
    gender: "Male",
    ip_address: "2.181.186.80",
  },
  {
    id: 27,
    first_name: "Gerick",
    last_name: "Northrop",
    email: "gnorthropq@ftc.gov",
    gender: "Male",
    ip_address: "8.76.95.76",
  },
  {
    id: 28,
    first_name: "Fidelia",
    last_name: "Plumley",
    email: "fplumleyr@yellowpages.com",
    gender: "Female",
    ip_address: "185.57.76.246",
  },
  {
    id: 29,
    first_name: "Kimberley",
    last_name: "Page",
    email: "kpages@imdb.com",
    gender: "Female",
    ip_address: "142.14.216.222",
  },
  {
    id: 30,
    first_name: "Gilbert",
    last_name: "Milton",
    email: "gmiltont@vk.com",
    gender: "Male",
    ip_address: "115.36.220.179",
  },
  {
    id: 31,
    first_name: "Gasper",
    last_name: "Mintoft",
    email: "gmintoftu@rambler.ru",
    gender: "Male",
    ip_address: "189.118.188.10",
  },
  {
    id: 32,
    first_name: "Caterina",
    last_name: "Melarkey",
    email: "cmelarkeyv@wsj.com",
    gender: "Female",
    ip_address: "180.33.13.72",
  },
  {
    id: 33,
    first_name: "Ade",
    last_name: "Penwell",
    email: "apenwellw@google.com",
    gender: "Male",
    ip_address: "36.187.209.31",
  },
  {
    id: 34,
    first_name: "Harry",
    last_name: "Rodrig",
    email: "hrodrigx@google.de",
    gender: "Male",
    ip_address: "33.232.216.31",
  },
  {
    id: 35,
    first_name: "Illa",
    last_name: "Thewles",
    email: "ithewlesy@angelfire.com",
    gender: "Female",
    ip_address: "41.253.138.217",
  },
  {
    id: 36,
    first_name: "Merrily",
    last_name: "Yates",
    email: "myatesz@ucoz.com",
    gender: "Female",
    ip_address: "36.23.167.59",
  },
  {
    id: 37,
    first_name: "Sergent",
    last_name: "Staddart",
    email: "sstaddart10@wsj.com",
    gender: "Male",
    ip_address: "107.101.214.57",
  },
  {
    id: 38,
    first_name: "Sharity",
    last_name: "Pettiford",
    email: "spettiford11@sciencedirect.com",
    gender: "Female",
    ip_address: "239.127.213.206",
  },
  {
    id: 39,
    first_name: "Abdul",
    last_name: "Coole",
    email: "acoole12@digg.com",
    gender: "Male",
    ip_address: "221.191.31.80",
  },
  {
    id: 40,
    first_name: "Jamison",
    last_name: "Leek",
    email: "jleek13@sphinn.com",
    gender: "Male",
    ip_address: "95.111.253.3",
  },
  {
    id: 41,
    first_name: "Gracie",
    last_name: "Piens",
    email: "gpiens14@vkontakte.ru",
    gender: "Female",
    ip_address: "9.251.16.121",
  },
  {
    id: 42,
    first_name: "Dan",
    last_name: "Simpkiss",
    email: "dsimpkiss15@sciencedirect.com",
    gender: "Male",
    ip_address: "133.212.186.224",
  },
  {
    id: 43,
    first_name: "Travis",
    last_name: "Hawkshaw",
    email: "thawkshaw16@jalbum.net",
    gender: "Male",
    ip_address: "151.85.57.68",
  },
  {
    id: 44,
    first_name: "Eolanda",
    last_name: "Pestell",
    email: "epestell17@1und1.de",
    gender: "Female",
    ip_address: "94.160.217.164",
  },
  {
    id: 45,
    first_name: "Grantham",
    last_name: "Tommasetti",
    email: "gtommasetti18@netvibes.com",
    gender: "Male",
    ip_address: "193.199.95.218",
  },
  {
    id: 46,
    first_name: "Bartolomeo",
    last_name: "Fairfoull",
    email: "bfairfoull19@walmart.com",
    gender: "Male",
    ip_address: "41.127.124.250",
  },
  {
    id: 47,
    first_name: "Herold",
    last_name: "Westhoff",
    email: "hwesthoff1a@ox.ac.uk",
    gender: "Male",
    ip_address: "130.253.45.181",
  },
  {
    id: 48,
    first_name: "Rowe",
    last_name: "Sutter",
    email: "rsutter1b@earthlink.net",
    gender: "Genderfluid",
    ip_address: "43.232.234.74",
  },
  {
    id: 49,
    first_name: "Caz",
    last_name: "Brownsword",
    email: "cbrownsword1c@smugmug.com",
    gender: "Male",
    ip_address: "108.4.103.101",
  },
  {
    id: 50,
    first_name: "Pepita",
    last_name: "Lennard",
    email: "plennard1d@globo.com",
    gender: "Female",
    ip_address: "110.241.40.229",
  },
  {
    id: 51,
    first_name: "Gearalt",
    last_name: "Gatecliff",
    email: "ggatecliff1e@plala.or.jp",
    gender: "Male",
    ip_address: "31.210.108.246",
  },
  {
    id: 52,
    first_name: "Marisa",
    last_name: "Gwillym",
    email: "mgwillym1f@goodreads.com",
    gender: "Female",
    ip_address: "40.233.88.212",
  },
  {
    id: 53,
    first_name: "Ingrid",
    last_name: "Cossor",
    email: "icossor1g@msu.edu",
    gender: "Female",
    ip_address: "228.42.56.37",
  },
  {
    id: 54,
    first_name: "Amos",
    last_name: "Trill",
    email: "atrill1h@freewebs.com",
    gender: "Male",
    ip_address: "228.212.228.40",
  },
  {
    id: 55,
    first_name: "Renaud",
    last_name: "Shovelin",
    email: "rshovelin1i@zdnet.com",
    gender: "Male",
    ip_address: "1.1.57.50",
  },
  {
    id: 56,
    first_name: "Jillian",
    last_name: "Pharaoh",
    email: "jpharaoh1j@phpbb.com",
    gender: "Agender",
    ip_address: "13.12.141.118",
  },
  {
    id: 57,
    first_name: "Lucie",
    last_name: "Petchey",
    email: "lpetchey1k@ebay.com",
    gender: "Female",
    ip_address: "197.2.49.235",
  },
  {
    id: 58,
    first_name: "Dawna",
    last_name: "Ollcott",
    email: "dollcott1l@thetimes.co.uk",
    gender: "Female",
    ip_address: "115.100.234.91",
  },
  {
    id: 59,
    first_name: "Johanna",
    last_name: "Dilke",
    email: "jdilke1m@unicef.org",
    gender: "Female",
    ip_address: "84.21.172.254",
  },
  {
    id: 60,
    first_name: "Gianni",
    last_name: "Beran",
    email: "gberan1n@blogger.com",
    gender: "Male",
    ip_address: "38.227.138.9",
  },
  {
    id: 61,
    first_name: "Arel",
    last_name: "Waszczykowski",
    email: "awaszczykowski1o@house.gov",
    gender: "Male",
    ip_address: "53.184.100.111",
  },
  {
    id: 62,
    first_name: "Cleve",
    last_name: "Danton",
    email: "cdanton1p@census.gov",
    gender: "Male",
    ip_address: "112.196.11.91",
  },
  {
    id: 63,
    first_name: "Spenser",
    last_name: "Klesse",
    email: "sklesse1q@nyu.edu",
    gender: "Genderfluid",
    ip_address: "171.176.8.235",
  },
  {
    id: 64,
    first_name: "Read",
    last_name: "Paolicchi",
    email: "rpaolicchi1r@howstuffworks.com",
    gender: "Male",
    ip_address: "241.146.179.129",
  },
  {
    id: 65,
    first_name: "Ainslie",
    last_name: "Nystrom",
    email: "anystrom1s@opera.com",
    gender: "Female",
    ip_address: "187.243.41.41",
  },
  {
    id: 66,
    first_name: "Lind",
    last_name: "Duddan",
    email: "lduddan1t@google.com.hk",
    gender: "Male",
    ip_address: "141.240.19.74",
  },
  {
    id: 67,
    first_name: "Ronni",
    last_name: "Bainbrigge",
    email: "rbainbrigge1u@upenn.edu",
    gender: "Female",
    ip_address: "250.232.230.50",
  },
  {
    id: 68,
    first_name: "Leslie",
    last_name: "McMeeking",
    email: "lmcmeeking1v@cnbc.com",
    gender: "Female",
    ip_address: "183.28.57.19",
  },
  {
    id: 69,
    first_name: "Brien",
    last_name: "Moseby",
    email: "bmoseby1w@hubpages.com",
    gender: "Male",
    ip_address: "219.127.183.199",
  },
  {
    id: 70,
    first_name: "Jenda",
    last_name: "Galia",
    email: "jgalia1x@accuweather.com",
    gender: "Female",
    ip_address: "66.82.185.216",
  },
  {
    id: 71,
    first_name: "Dylan",
    last_name: "Cattach",
    email: "dcattach1y@networksolutions.com",
    gender: "Male",
    ip_address: "173.215.227.125",
  },
  {
    id: 72,
    first_name: "Marie-jeanne",
    last_name: "MacAllaster",
    email: "mmacallaster1z@omniture.com",
    gender: "Female",
    ip_address: "52.67.203.101",
  },
  {
    id: 73,
    first_name: "Esta",
    last_name: "Radnage",
    email: "eradnage20@ucoz.com",
    gender: "Female",
    ip_address: "208.57.172.247",
  },
  {
    id: 74,
    first_name: "Jillane",
    last_name: "Devonside",
    email: "jdevonside21@shutterfly.com",
    gender: "Female",
    ip_address: "190.26.124.232",
  },
  {
    id: 75,
    first_name: "Leyla",
    last_name: "Fullerton",
    email: "lfullerton22@un.org",
    gender: "Female",
    ip_address: "151.253.21.52",
  },
  {
    id: 76,
    first_name: "Marchall",
    last_name: "Shutte",
    email: "mshutte23@sbwire.com",
    gender: "Male",
    ip_address: "197.184.95.74",
  },
  {
    id: 77,
    first_name: "Nichole",
    last_name: "Tortoishell",
    email: "ntortoishell24@facebook.com",
    gender: "Agender",
    ip_address: "154.53.231.233",
  },
  {
    id: 78,
    first_name: "Sheela",
    last_name: "Hasely",
    email: "shasely25@meetup.com",
    gender: "Female",
    ip_address: "1.12.150.140",
  },
  {
    id: 79,
    first_name: "Annabella",
    last_name: "Biggs",
    email: "abiggs26@blogs.com",
    gender: "Female",
    ip_address: "107.36.18.39",
  },
  {
    id: 80,
    first_name: "Jephthah",
    last_name: "Schultheiss",
    email: "jschultheiss27@zdnet.com",
    gender: "Polygender",
    ip_address: "121.119.126.98",
  },
  {
    id: 81,
    first_name: "Hewe",
    last_name: "Coxon",
    email: "hcoxon28@eepurl.com",
    gender: "Male",
    ip_address: "178.236.223.41",
  },
  {
    id: 82,
    first_name: "Danny",
    last_name: "Milazzo",
    email: "dmilazzo29@harvard.edu",
    gender: "Male",
    ip_address: "246.26.75.6",
  },
  {
    id: 83,
    first_name: "Nixie",
    last_name: "Joust",
    email: "njoust2a@yandex.ru",
    gender: "Female",
    ip_address: "193.194.156.207",
  },
  {
    id: 84,
    first_name: "Marga",
    last_name: "Paule",
    email: "mpaule2b@vimeo.com",
    gender: "Female",
    ip_address: "8.103.197.197",
  },
  {
    id: 85,
    first_name: "Jessy",
    last_name: "Andree",
    email: "jandree2c@etsy.com",
    gender: "Female",
    ip_address: "141.63.152.140",
  },
  {
    id: 86,
    first_name: "Alvira",
    last_name: "Phythean",
    email: "aphythean2d@eepurl.com",
    gender: "Bigender",
    ip_address: "17.247.152.65",
  },
  {
    id: 87,
    first_name: "Julian",
    last_name: "Guerriero",
    email: "jguerriero2e@washington.edu",
    gender: "Male",
    ip_address: "144.56.4.241",
  },
  {
    id: 88,
    first_name: "Baillie",
    last_name: "Meriel",
    email: "bmeriel2f@lulu.com",
    gender: "Male",
    ip_address: "150.17.127.150",
  },
  {
    id: 89,
    first_name: "Brent",
    last_name: "Claeskens",
    email: "bclaeskens2g@rakuten.co.jp",
    gender: "Male",
    ip_address: "50.140.138.182",
  },
  {
    id: 90,
    first_name: "Mitchel",
    last_name: "Drever",
    email: "mdrever2h@bravesites.com",
    gender: "Male",
    ip_address: "129.107.66.29",
  },
  {
    id: 91,
    first_name: "Bettine",
    last_name: "Royson",
    email: "broyson2i@sciencedaily.com",
    gender: "Female",
    ip_address: "87.105.201.176",
  },
  {
    id: 92,
    first_name: "Bernetta",
    last_name: "Kornyshev",
    email: "bkornyshev2j@vk.com",
    gender: "Female",
    ip_address: "255.177.22.232",
  },
  {
    id: 93,
    first_name: "Donnajean",
    last_name: "Cambridge",
    email: "dcambridge2k@godaddy.com",
    gender: "Female",
    ip_address: "133.129.169.19",
  },
  {
    id: 94,
    first_name: "Beth",
    last_name: "Rheaume",
    email: "brheaume2l@vinaora.com",
    gender: "Female",
    ip_address: "171.13.33.156",
  },
  {
    id: 95,
    first_name: "Matilda",
    last_name: "Iredale",
    email: "miredale2m@noaa.gov",
    gender: "Female",
    ip_address: "186.21.220.187",
  },
  {
    id: 96,
    first_name: "Zebedee",
    last_name: "Cammack",
    email: "zcammack2n@wufoo.com",
    gender: "Male",
    ip_address: "37.21.135.184",
  },
  {
    id: 97,
    first_name: "Heath",
    last_name: "Veneur",
    email: "hveneur2o@alexa.com",
    gender: "Female",
    ip_address: "237.131.196.242",
  },
  {
    id: 98,
    first_name: "Agathe",
    last_name: "Louthe",
    email: "alouthe2p@networkadvertising.org",
    gender: "Female",
    ip_address: "31.39.169.228",
  },
  {
    id: 99,
    first_name: "Moira",
    last_name: "Essel",
    email: "messel2q@linkedin.com",
    gender: "Female",
    ip_address: "101.130.23.200",
  },
  {
    id: 100,
    first_name: "Hynda",
    last_name: "Lydiatt",
    email: "hlydiatt2r@cnbc.com",
    gender: "Agender",
    ip_address: "95.168.189.171",
  },
];

const columns: GridColDef[] = [
  { field: "id", headerName: "ID", width: 90,align:'center'},
  {
    field: "first_name",
    headerName: "First name",
    width: 150,
    editable: true,
  },
  {
    field: "last_name",
    headerName: "Last name",
    width: 150,
    editable: true,
  },
  {
    field: "email",
    headerName: "Email",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "gender",
    headerName: "Gender",
    description: "This column has a value getter and is not sortable.",
    sortable: false,
    width: 160,
  },
];

const paginationModel = { page: 0, pageSize: 10};

const MuiDataGrid = () => {
  return (
    <Box
      sx={{
        width: "90%",
        height: "80%",
      }}
    >
      <DataGrid
        checkboxSelection
        rows={data}
        columns={columns}
        initialState={{ pagination: { paginationModel } }}
        pageSizeOptions={[10]}
      ></DataGrid>
    </Box>
  );
};

export default MuiDataGrid;
